<?php

namespace App\Support;

use BackedEnum;
use Illuminate\Support\Str;
use ReflectionEnum;
use Symfony\Component\Finder\Finder;

/**
 * Turns the backend's backed enums (app/Enums) into a TypeScript module so the
 * app uses exactly the same status values (Technical standards: "status values
 * are fixed lists shared by frontend and backend").
 *
 * An enum may define `label(): string` on its cases; labels are exported too.
 */
final class EnumExporter
{
    /** @return list<class-string<BackedEnum>> */
    public static function discover(string $directory, string $namespace = 'App\\Enums'): array
    {
        if (! is_dir($directory)) {
            return [];
        }

        $classes = [];

        foreach (Finder::create()->files()->name('*.php')->in($directory)->sortByName() as $file) {
            $relative = str_replace(['/', '.php'], ['\\', ''], $file->getRelativePathname());
            $class = $namespace.'\\'.$relative;

            if (enum_exists($class) && (new ReflectionEnum($class))->isBacked()) {
                $classes[] = $class;
            }
        }

        return $classes;
    }

    /** @param  list<class-string<BackedEnum>>  $enums */
    public static function toTypeScript(array $enums): string
    {
        $out = [
            '// AUTO-GENERATED by `php artisan boardmate:export-enums`. Do not edit by hand.',
            '// Source: boardmate/app/Enums',
            '',
        ];

        foreach ($enums as $enum) {
            $name = class_basename($enum);
            $cases = $enum::cases();

            $out[] = "export const {$name} = {";
            foreach ($cases as $case) {
                $out[] = '  '.Str::studly($case->name).': '.self::literal($case->value).',';
            }
            $out[] = '} as const';
            $out[] = "export type {$name} = (typeof {$name})[keyof typeof {$name}]";

            if ($cases !== [] && method_exists($cases[0], 'label')) {
                $out[] = "export const {$name}Labels: Record<{$name}, string> = {";
                foreach ($cases as $case) {
                    $out[] = '  '.self::literal($case->value).': '.self::literal($case->label()).',';
                }
                $out[] = '}';
            }

            $out[] = '';
        }

        return implode("\n", $out);
    }

    private static function literal(string|int $value): string
    {
        return is_int($value) ? (string) $value : "'".addcslashes($value, "'\\")."'";
    }
}
